[package]
name = "BlazeFTCQuickstart"
version = "0.1.0"
edition = "2024"

[dependencies]
jni = "0.21.1"
#blaze_ftc = { version = "0.1.0", path = "../blaze_ftc" }
#eventually we should do this better, but for now I'm pinning it to a commit
blaze_ftc = { version = "0.1.0", git = "https://github.com/owenpmckenna/blaze_ftc", rev = "d389b8f" }
log = "0.4.29"

[lib]
name = "blaze_ftc_quickstart"
path = "src/lib.rs"
crate-type = ["cdylib"]
